"""Policy-result exit codes used by user-facing commands."""

SUCCESS = 0
GENERIC_ERROR = 1

POLICY_RESULT = 0x40
RUNTIME_PHASE = 0x10
RELEASE_PHASE = 0x20

CAPABILITY_BIT = 0x02
GATE_BIT = 0x04
WORKLOAD_BIT = 0x08

CAPABILITY_APPLICATION_FAILURE = POLICY_RESULT | CAPABILITY_BIT
GATE_APPLICATION_FAILURE = POLICY_RESULT | GATE_BIT
FATAL_RUNTIME_CAPABILITY_VIOLATION = POLICY_RESULT | RUNTIME_PHASE | CAPABILITY_BIT
RUNTIME_GATE_POLICY_VIOLATION = POLICY_RESULT | RUNTIME_PHASE | GATE_BIT
RUNTIME_WORKLOAD_TERMINATION_FAILURE = POLICY_RESULT | RUNTIME_PHASE | WORKLOAD_BIT
CAPABILITY_RELEASE_FAILURE = POLICY_RESULT | RELEASE_PHASE | CAPABILITY_BIT
GATE_RELEASE_FAILURE = POLICY_RESULT | RELEASE_PHASE | GATE_BIT
CAPABILITY_AND_GATE_RELEASE_FAILURE = (
    POLICY_RESULT | RELEASE_PHASE | CAPABILITY_BIT | GATE_BIT
)
RELEASE_BLOCKED_BY_ACTIVE_WORKLOAD_TERMINATION_FAILURE = (
    POLICY_RESULT | RELEASE_PHASE | WORKLOAD_BIT
)
